export interface CSSDict {
  accentColor: string;
  alignContent: string;
  alignItems: string;
  alignSelf: string;
  alignmentBaseline: string;
  all: string;
  animation: string;
  animationComposition: string;
  animationDelay: string;
  animationDirection: string;
  animationDuration: string;
  animationFillMode: string;
  animationIterationCount: string;
  animationName: string;
  animationPlayState: string;
  animationTimingFunction: string;
  appearance: string;
  aspectRatio: string;
  backdropFilter: string;
  backfaceVisibility: string;
  background: string;
  backgroundAttachment: string;
  backgroundBlendMode: string;
  backgroundClip: string;
  backgroundColor: string;
  backgroundImage: string;
  backgroundOrigin: string;
  backgroundPosition: string;
  backgroundPositionX: string;
  backgroundPositionY: string;
  backgroundRepeat: string;
  backgroundSize: string | number;
  baselineShift: string;
  baselineSource: string;
  blockSize: string | number;
  border: string;
  borderBlock: string;
  borderBlockColor: string;
  borderBlockEnd: string;
  borderBlockEndColor: string;
  borderBlockEndStyle: string;
  borderBlockEndWidth: string | number;
  borderBlockStart: string;
  borderBlockStartColor: string;
  borderBlockStartStyle: string;
  borderBlockStartWidth: string | number;
  borderBlockStyle: string;
  borderBlockWidth: string | number;
  borderBottom: string;
  borderBottomColor: string;
  borderBottomLeftRadius: string;
  borderBottomRightRadius: string;
  borderBottomStyle: string;
  borderBottomWidth: string | number;
  borderCollapse: string;
  borderColor: string;
  borderEndEndRadius: string;
  borderEndStartRadius: string;
  borderImage: string;
  borderImageOutset: string;
  borderImageRepeat: string;
  borderImageSlice: string;
  borderImageSource: string;
  borderImageWidth: string | number;
  borderInline: string;
  borderInlineColor: string;
  borderInlineEnd: string;
  borderInlineEndColor: string;
  borderInlineEndStyle: string;
  borderInlineEndWidth: string | number;
  borderInlineStart: string;
  borderInlineStartColor: string;
  borderInlineStartStyle: string;
  borderInlineStartWidth: string | number;
  borderInlineStyle: string;
  borderInlineWidth: string | number;
  borderLeft: string;
  borderLeftColor: string;
  borderLeftStyle: string;
  borderLeftWidth: string | number;
  borderRadius: string;
  borderRight: string;
  borderRightColor: string;
  borderRightStyle: string;
  borderRightWidth: string | number;
  borderSpacing: string | number;
  borderStartEndRadius: string;
  borderStartStartRadius: string;
  borderStyle: string;
  borderTop: string;
  borderTopColor: string;
  borderTopLeftRadius: string;
  borderTopRightRadius: string;
  borderTopStyle: string;
  borderTopWidth: string | number;
  borderWidth: string | number;
  bottom: string | number;
  boxShadow: string;
  boxSizing: string;
  breakAfter: string;
  breakBefore: string;
  breakInside: string;
  captionSide: string;
  caretColor: string;
  clear: string;
  clipPath: string;
  clipRule: string;
  color: string;
  colorInterpolation: string;
  colorInterpolationFilters: string;
  colorScheme: string;
  columnCount: string;
  columnFill: string;
  columnGap: string | number;
  columnRule: string;
  columnRuleColor: string;
  columnRuleStyle: string;
  columnRuleWidth: string | number;
  columnSpan: string;
  columnWidth: string | number;
  columns: string;
  contain: string;
  containIntrinsicBlockSize: string | number;
  containIntrinsicHeight: string | number;
  containIntrinsicInlineSize: string | number;
  containIntrinsicSize: string | number;
  containIntrinsicWidth: string | number;
  container: string;
  containerName: string;
  containerType: string;
  content: string;
  contentVisibility: string;
  counterIncrement: string;
  counterReset: string;
  counterSet: string;
  cssFloat: string;
  cssText: string;
  cursor: string;
  cx: string;
  cy: string;
  d: string;
  direction: string;
  display: string;
  dominantBaseline: string;
  emptyCells: string;
  fill: string;
  fillOpacity: string;
  fillRule: string;
  filter: string;
  flex: string;
  flexBasis: string;
  flexDirection: string;
  flexFlow: string;
  flexGrow: string;
  flexShrink: string;
  flexWrap: string;
  float: string;
  floodColor: string;
  floodOpacity: string;
  font: string;
  fontFamily: string;
  fontFeatureSettings: string;
  fontKerning: string;
  fontOpticalSizing: string;
  fontPalette: string;
  fontSize: string | number;
  fontSizeAdjust: string;
  fontStretch: string;
  fontStyle: string;
  fontSynthesis: string;
  fontSynthesisSmallCaps: string;
  fontSynthesisStyle: string;
  fontSynthesisWeight: string;
  fontVariant: string;
  fontVariantAlternates: string;
  fontVariantCaps: string;
  fontVariantEastAsian: string;
  fontVariantLigatures: string;
  fontVariantNumeric: string;
  fontVariantPosition: string;
  fontVariationSettings: string;
  fontWeight: string;
  forcedColorAdjust: string;
  gap: string | number;
  grid: string;
  gridArea: string;
  gridAutoColumns: string;
  gridAutoFlow: string;
  gridAutoRows: string;
  gridColumn: string;
  gridColumnEnd: string;
  gridColumnGap: string | number;
  gridColumnStart: string;
  gridGap: string | number;
  gridRow: string;
  gridRowEnd: string;
  gridRowGap: string | number;
  gridRowStart: string;
  gridTemplate: string;
  gridTemplateAreas: string;
  gridTemplateColumns: string;
  gridTemplateRows: string;
  height: string | number;
  hyphenateCharacter: string;
  hyphens: string;
  imageRendering: string;
  inlineSize: string | number;
  inset: string;
  insetBlock: string;
  insetBlockEnd: string;
  insetBlockStart: string;
  insetInline: string;
  insetInlineEnd: string;
  insetInlineStart: string;
  isolation: string;
  justifyContent: string;
  justifyItems: string;
  justifySelf: string;
  left: string | number;
  letterSpacing: string | number;
  lightingColor: string;
  lineBreak: string;
  lineHeight: string | number;
  listStyle: string;
  listStyleImage: string;
  listStylePosition: string;
  listStyleType: string;
  margin: string | number;
  marginBlock: string | number;
  marginBlockEnd: string | number;
  marginBlockStart: string | number;
  marginBottom: string | number;
  marginInline: string | number;
  marginInlineEnd: string | number;
  marginInlineStart: string | number;
  marginLeft: string | number;
  marginRight: string | number;
  marginTop: string | number;
  marker: string;
  markerEnd: string;
  markerMid: string;
  markerStart: string;
  mask: string;
  maskClip: string;
  maskComposite: string;
  maskImage: string;
  maskMode: string;
  maskOrigin: string;
  maskPosition: string;
  maskRepeat: string;
  maskSize: string | number;
  maskType: string;
  mathDepth: string;
  mathStyle: string;
  maxBlockSize: string | number;
  maxHeight: string | number;
  maxInlineSize: string | number;
  maxWidth: string | number;
  minBlockSize: string | number;
  minHeight: string | number;
  minInlineSize: string | number;
  minWidth: string | number;
  mixBlendMode: string;
  objectFit: string;
  objectPosition: string;
  offset: string;
  offsetAnchor: string;
  offsetDistance: string;
  offsetPath: string;
  offsetPosition: string;
  offsetRotate: string;
  opacity: string;
  order: string;
  orphans: string;
  outline: string;
  outlineColor: string;
  outlineOffset: string;
  outlineStyle: string;
  outlineWidth: string | number;
  overflow: string;
  overflowAnchor: string;
  overflowClipMargin: string | number;
  overflowWrap: string;
  overflowX: string;
  overflowY: string;
  overscrollBehavior: string;
  overscrollBehaviorBlock: string;
  overscrollBehaviorInline: string;
  overscrollBehaviorX: string;
  overscrollBehaviorY: string;
  padding: string | number;
  paddingBlock: string | number;
  paddingBlockEnd: string | number;
  paddingBlockStart: string | number;
  paddingBottom: string | number;
  paddingInline: string | number;
  paddingInlineEnd: string | number;
  paddingInlineStart: string | number;
  paddingLeft: string | number;
  paddingRight: string | number;
  paddingTop: string | number;
  page: string;
  pageBreakAfter: string;
  pageBreakBefore: string;
  pageBreakInside: string;
  paintOrder: string;
  perspective: string | number;
  perspectiveOrigin: string;
  placeContent: string;
  placeItems: string;
  placeSelf: string;
  pointerEvents: string;
  position: string;
  printColorAdjust: string;
  quotes: string;
  r: string;
  resize: string;
  right: string | number;
  rotate: string;
  rowGap: string | number;
  rubyPosition: string;
  rx: string;
  ry: string;
  scale: string;
  scrollBehavior: string;
  scrollMargin: string | number;
  scrollMarginBlock: string | number;
  scrollMarginBlockEnd: string | number;
  scrollMarginBlockStart: string | number;
  scrollMarginBottom: string | number;
  scrollMarginInline: string | number;
  scrollMarginInlineEnd: string | number;
  scrollMarginInlineStart: string | number;
  scrollMarginLeft: string | number;
  scrollMarginRight: string | number;
  scrollMarginTop: string | number;
  scrollPadding: string | number;
  scrollPaddingBlock: string | number;
  scrollPaddingBlockEnd: string | number;
  scrollPaddingBlockStart: string | number;
  scrollPaddingBottom: string | number;
  scrollPaddingInline: string | number;
  scrollPaddingInlineEnd: string | number;
  scrollPaddingInlineStart: string | number;
  scrollPaddingLeft: string | number;
  scrollPaddingRight: string | number;
  scrollPaddingTop: string | number;
  scrollSnapAlign: string;
  scrollSnapStop: string;
  scrollSnapType: string;
  scrollbarColor: string;
  scrollbarGutter: string;
  scrollbarWidth: string | number;
  shapeImageThreshold: string;
  shapeMargin: string | number;
  shapeOutside: string;
  shapeRendering: string;
  stopColor: string;
  stopOpacity: string;
  stroke: string;
  strokeDasharray: string;
  strokeDashoffset: string;
  strokeLinecap: string;
  strokeLinejoin: string;
  strokeMiterlimit: string;
  strokeOpacity: string;
  strokeWidth: string | number;
  tabSize: string | number;
  tableLayout: string;
  textAlign: string;
  textAlignLast: string;
  textAnchor: string;
  textCombineUpright: string;
  textDecoration: string;
  textDecorationColor: string;
  textDecorationLine: string;
  textDecorationSkipInk: string;
  textDecorationStyle: string;
  textDecorationThickness: string;
  textEmphasis: string;
  textEmphasisColor: string;
  textEmphasisPosition: string;
  textEmphasisStyle: string;
  textIndent: string | number;
  textOrientation: string;
  textOverflow: string;
  textRendering: string;
  textShadow: string;
  textTransform: string;
  textUnderlineOffset: string;
  textUnderlinePosition: string;
  textWrap: string;
  textWrapMode: string;
  textWrapStyle: string;
  top: string | number;
  touchAction: string;
  transform: string;
  transformBox: string;
  transformOrigin: string;
  transformStyle: string;
  transition: string;
  transitionBehavior: string;
  transitionDelay: string;
  transitionDuration: string;
  transitionProperty: string;
  transitionTimingFunction: string;
  translate: string;
  unicodeBidi: string;
  userSelect: string;
  vectorEffect: string;
  verticalAlign: string;
  visibility: string;
  webkitLineClamp: string;
  webkitTextFillColor: string;
  webkitTextStroke: string;
  webkitTextStrokeColor: string;
  webkitTextStrokeWidth: string | number;
  whiteSpace: string;
  whiteSpaceCollapse: string;
  widows: string;
  width: string | number;
  willChange: string;
  wordBreak: string;
  wordSpacing: string | number;
  wordWrap: string;
  writingMode: string;
  x: string;
  y: string;
  zIndex: string;
  zoom: string;
}
